services:
  db:
    image: postgres:15-alpine
    container_name: fastapi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "55433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
      image : redis:alpine
      container_name: redis
      ports :
        - '6379:6379'
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 30s
        retries: 5
        start_period: 30s
  locust:
    image: locustio/locust
    ports:
      - '8089:8089'
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py
  
  todo-backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    container_name: todo-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app/src  
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres123@db:5432/postgres
      SECRET_KEY: z_f%#7x&0!n6uuamyca%y5swv1(9e=u=wu9s#wy(3f-k__k777
      REDIS_URL: redis://redis:6379
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:50'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtpdev
volumes:
  smtp4dev-data: